# Autogenerated (Do not edit)

require "formula"
require_relative "lib/private_strategy"

class Aard < Formula
  desc "aard is Aardvark's CLI"
  homepage "https://aardvarklabs.com/"
  url "https://github.com/aardlabs/homebrew-cli/releases/download/v0.9.9/aard-darwin-amd64-v0.9.9.zip"
  sha256 "d6bf6ebaabcca4bfa615124c01b908d5117c098c60380d3d044694d9ddc6d249"
  head "https://github.com/aardlabs/homebrew-cli.git"
  # depends_on "coreutils"

  def install
    libexec.install Dir["*"]
    bin.install_symlink libexec/"aard"
    (bash_completion/"aard").write `#{bin}/aard completion -s bash`
    (fish_completion/"aard.fish").write `#{bin}/aard completion -s fish`
    (zsh_completion/"_aard").write `#{bin}/aard completion -s zsh`
  end

  def caveats
    <<~EOS
      aard is the aardvark CLI.

      * Once installed, you can run the following command to help get started

        $ aard --help

    EOS
  end

  # Homebrew requires tests.
  test do
    assert_match "0.9.9", shell_output("#{bin}/aard --version", 2)
  end
end