# Autogenerated (Do not edit)

require "formula"
require_relative "lib/private_strategy"

class Aard < Formula
  desc "aard is Aardvark's CLI"
  homepage "https://aardvarklabs.com/"
  url "https://github.com/aardlabs/homebrew-cli/releases/download/v0.9.8/aard-darwin-amd64-v0.9.8.zip"
  sha256 "cb9c0f4c43e9fb3b529d78cd048893087ef9bf65aafd2f8531d6be5725725e87"
  head "https://github.com/aardlabs/homebrew-cli.git"
  # depends_on "coreutils"

  def install
    libexec.install Dir["*"]
    bin.install_symlink libexec/"aard"
    (bash_completion/"aard").write `#{bin}/aard completion -s bash`
    (fish_completion/"aard.fish").write `#{bin}/aard completion -s fish`
    (zsh_completion/"_aard").write `#{bin}/aard completion -s zsh`
  end

  def caveats
    <<~EOS
      aard is the aardvark CLI.

      * Once installed, you can run the following command to help get started

        $ aard --help

    EOS
  end

  # Homebrew requires tests.
  test do
    assert_match "0.9.8", shell_output("#{bin}/aard --version", 2)
  end
end